
I18n.translations["en-GB"] = {

	hello: "Invite easy",
	enter: "Enter",
	back: "Back",
	login: "Login",
	logout: "Logout",
	email: "Email",
	save: "Save",
	submit: "Submit",
	create: "Create",
	edit: "Edit",
	zip: "Zip",
	address: "Address",
  exchanged_invitation: "Exchanged",
	add: "Add",
	username: "Username",
	password: "Password",
  "promos-option-stopped": "Stopped",
  "promos-option-running": "Running",
	reconnect: "Reconnect",
	login_msg_reconnect: "Your network activity is likely inactive",
	scan_title: "Scan your code",
	scan_help: "Puts the phone in front of the reader. If you have any problems do not hesitate to go to the local dependent.",
	scan: "Scan",
	search: "Search",
	identifier: "Identifier",
	other_products: "Other products",
	invited_by: "Invited by",
	consignee: 'Consignee',
	checkin_gifts: 'Checkin gifts',
	confirm: "Confirm",
	environment: "Environment",
  sandbox_env: "Sandbox",
  live_env: "Live",
	move_to_live: "Move to Live",
	move_to_sandbox: "Move to Sandbox",
	something_else_title: "Do you want more?",
	something_else_placeholder: "Place the desire",
	invitation_code_placeholder: "Code",
	empty_invitations: "You have no invitations",
	empty_promos: "Add a promo to start",
	succeed_consumed_invitation: "The invitation has been consumed",
	about_us: "About us",
  login_incorrect: "Username or password is wrong",
  popup_title: 'Invibe',

	message_generic_error: "An error occurred",
  notification_inactive_internet_connection: "Internet connection is likely inactive. Please, reconnect to continue",
  ask_manual_code: "Manual code? Redeem here",

	close_session: "Close session",


	camera_front: "Using Front",
	camera_back: "Using Back",
	camera_device: "Change Device Camera",

  current_password: "Current password",
  new_password: "New password",
  confirm_password: "Confirm new password",

  menu_scan: "Scan",
  menu_invitations: "Pending Invitations",
  menu_promos: "Promotions",
  menu_reports: "Reports",
  menu_settings: "Settings",

  error_password_different: 'Confirmation password was wrong',

	promos_title: "Promotions",
	password_title: "Change Password",
	promo_title: "Promotion",
	settings_title: "Settings",
	reports_title: "Reports",

	free: "Free",
	currency_symbol: '£',
	currency_code: 'GBP'

};
